M48
; DRILL file KiCad 10.0.1 date 2026-06-26T16:38:36
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-06-26T16:38:36+09:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.700
%
G90
G05
T1
X172.004Y-124.364
X177.784Y-124.364
T2
X2.975Y-2.975
X2.975Y-9.925
X2.975Y-16.875
X2.975Y-23.825
M30
